spring:
  data:
    mongodb:
      database: Teachers
      host: mongodb
      port: 27017
  freemarker:
    suffix: .ftl


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always